"""empty message

Revision ID: 0075939050f7
Revises: 704670cab4ab
Create Date: 2022-10-31 12:38:33.380716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0075939050f7'
down_revision = '704670cab4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('handlebars', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'handlebars')
    # ### end Alembic commands ###
