"""empty message

<<<<<<<< HEAD:migrations/versions/5a3501521aa6_.py
Revision ID: 5a3501521aa6
Revises: 
Create Date: 2022-10-31 12:38:39.264596
========
Revision ID: 704670cab4ab
Revises: 
Create Date: 2022-10-31 12:37:49.788198
>>>>>>>> 2c02039eb2112a71ccc7234298d62b72ed9d5097:migrations/versions/704670cab4ab_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3501521aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('kendallisgreat', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bike')
    # ### end Alembic commands ###
